# Naive Bayes 실습

1. Gaussian Naive Bayes
- 데이터, 모듈 불러오기

In [ ]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB # naive bayes 모듈에서 GaussianNB 함수 불러오기

In [ ]:
import pandas as pd

In [ ]:
iris = datasets.load_iris() # iris 데이터 불러오기
df_X = pd.DataFrame(iris.data) #X,Y를 DataFrame으로
df_Y = pd.DataFrame(iris.target)

In [ ]:
df_X.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [ ]:
df_Y.head()

0
0  0
1  0
2  0
3  0
4  0

- 모델 피팅

In [ ]:
gnb=GaussianNB()
fitted=gnb.fit(iris.data,iris.target)
y_pred=fitted.predict(iris.data)

In [ ]:
fitted.predict_proba(iris.data)[[1,48,51,100]] # 1,48,51,100번째 데이터가 0,1,2일 확률을 보여주는 proba

array([[1.00000000e+000, 1.51480769e-017, 2.34820051e-025],
       [1.00000000e+000, 2.63876217e-018, 2.79566024e-025],
       [7.27347795e-102, 9.45169639e-001, 5.48303606e-002],
       [3.23245181e-254, 6.35381031e-011, 1.00000000e+000]])

In [ ]:
fitted.predict(iris.data)[[1,48,51,100]]# 1,48,51,100번째 데이터 예측값

array([0, 0, 1, 2])

- Confusion matrix 구하기

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(iris.target, y_pred)
# 트라이얼을 하나도안준것은 0인 것을 잘 맞췄음
# 1,2인것도 나름 잘 맞췄으나 3개는 틀렸음


array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]])

- Prior 설정하기 (특정 범주일 확률을 바꿔줄 수 있음)

In [ ]:
gnb2 = GaussianNB(priors=[1/100,1/100,98/100]) # 3개의 범주(0,1,2)를 각각의 설정한 확률로 바꾸는 작업
fitted2 = gnb2.fit(iris.data,iris.target)
y_pred2=fitted2.predict(iris.data) # prediction한 결과값을 pred2에 저장
confusion_matrix(iris.target, y_pred2)

# 3번째(2인 것들)가 나올 확률을 막 높였더니 3번째인것들을 다 맞추었으나 대신 1번째, 2번째를 적게 나오게 했으니 2번째를 3번째로 인식하게되는 trade off가 발생함
 


array([[50,  0,  0],
       [ 0, 33, 17],
       [ 0,  0, 50]])

In [ ]:
# 다른 트라이얼 값
gnb2 = GaussianNB(priors=[1/100,98/100,1/100]) # 3개의 범주(0,1,2)를 각각의 설정한 확률로 바꾸는 작업
fitted2 = gnb2.fit(iris.data,iris.target)
y_pred2=fitted2.predict(iris.data) # prediction한 결과값을 pred2에 저장
confusion_matrix(iris.target, y_pred2)

# 2번째 범주를 높였더니 3번째 범주에서 틀리는 경우가 많이 발생함

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0, 14, 36]])

# 2. Multinomial naive bayes

- 모듈 불러오기 및 데이터 생성


In [ ]:
from sklearn.naive_bayes import MultinomialNB 

In [ ]:
import numpy as np

In [ ]:
# 변수가 100개고 sample size가 6개인
X = np.random.randint(5, size=(6,100))
y = np.array([1,2,3,4,5,6])

In [ ]:
X

array([[1, 4, 4, 2, 3, 2, 1, 4, 2, 2, 2, 1, 1, 2, 4, 4, 0, 3, 1, 2, 1, 1,
        2, 2, 2, 2, 0, 2, 1, 0, 3, 3, 0, 4, 0, 4, 1, 3, 3, 4, 2, 4, 2, 2,
        2, 1, 0, 1, 3, 1, 1, 2, 2, 3, 0, 1, 0, 2, 2, 3, 3, 4, 2, 0, 3, 2,
        0, 1, 4, 0, 4, 4, 1, 0, 2, 1, 0, 4, 2, 2, 0, 0, 1, 1, 0, 0, 1, 3,
        0, 3, 2, 3, 1, 0, 4, 2, 0, 4, 1, 2],
       [0, 1, 2, 2, 2, 3, 3, 4, 4, 1, 0, 3, 2, 1, 4, 0, 4, 4, 0, 4, 0, 0,
        3, 4, 2, 1, 3, 1, 4, 2, 2, 4, 4, 4, 2, 2, 2, 1, 1, 2, 0, 0, 1, 2,
        3, 3, 1, 4, 3, 4, 1, 0, 2, 3, 4, 4, 1, 3, 3, 2, 3, 1, 2, 3, 2, 2,
        3, 3, 0, 1, 0, 4, 3, 4, 3, 1, 2, 2, 3, 0, 1, 3, 3, 2, 0, 3, 2, 4,
        2, 3, 1, 2, 0, 3, 4, 4, 1, 4, 1, 4],
       [2, 4, 1, 1, 3, 4, 0, 1, 3, 4, 0, 0, 4, 3, 0, 0, 1, 3, 3, 2, 0, 1,
        2, 0, 4, 1, 2, 3, 1, 4, 0, 1, 2, 3, 1, 3, 2, 3, 4, 3, 4, 0, 0, 3,
        1, 4, 2, 2, 1, 3, 1, 2, 0, 1, 0, 2, 3, 4, 3, 1, 4, 1, 2, 1, 4, 1,
        0, 3, 0, 3, 1, 0, 1, 0, 3, 3, 4, 2, 1, 4, 4, 1, 3, 0, 0, 1, 2, 0,
        1, 2, 1, 1, 3,

In [ ]:
y
# y가 1~6까지의 클래스

array([1, 2, 3, 4, 5, 6])

- Multinomial naive bayes 모델 생성

In [ ]:
clf = MultinomialNB()
clf.fit(X,y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
print(clf.predict(X[2:3])) # 2번째 관측치를 가지고 왔을때 다음과 같이 predict가 된다.

[3]


In [ ]:
clf.predict_proba(X[2:3]) # 2번째 관측치가 1~6번째 범주일 확률 (ex. 3번째관측치가 될 확률이 1이다.)

array([[9.70243966e-32, 3.28760646e-32, 1.00000000e+00, 7.21679138e-37,
        1.67814462e-33, 2.60178970e-31]])

- prior 변경해보기

In [ ]:
clf2 = MultinomialNB(class_prior=[0.1,0.5,0.1,0.1,0.1,0.1]) # 다른건 똑같고 2번째 3번째 범주의 확률만 바꾼것
clf2.fit(X,y)

MultinomialNB(alpha=1.0, class_prior=[0.1, 0.5, 0.1, 0.1, 0.1, 0.1],
              fit_prior=True)

In [ ]:
clf2.predict_proba(X[2:3]) 
# 웨어트를 많이준 2번째를 보면 프라이얼을 변경하지 않은 것에 비해 상승하는것을 볼수있음
# 아닌값은 하락

array([[9.70243966e-32, 1.64380323e-31, 1.00000000e+00, 7.21679138e-37,
        1.67814462e-33, 2.60178970e-31]])

# prior을 활용해서 Gaussian Naive Bayes, Multinomial Naive Bayes